todoApp/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::resource('todoapp', 'TodosController') ; 

Route::post('todoapp/complete/{id}', 'TodosController@complete') ; 

todoApp/app/Todo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Todo extends Model
{
   
protected   $fillable  = [
		 			'title', 
		 			'body', 
		 			'is_completed', 
		 			'completion_time'
		 	] ; 

}

todoApp/app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];
}

todoApp/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

abstract class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

todoApp/app/Http/Controllers/TodosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Todo ; 
class TodosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $todos = Todo::paginate(10)   ;
        $todos->setPath('todoapp') ; 
        return view('todos', compact('todos')) ; 

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('todo-create') ; 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $todo = new Todo($request->all()) ;
         // dd($request->all() ) ;
         // $todo->title =  $request->all()['title'] ; 
         // $todo->body = $request->all()['body']; 
         // $todo->is_completed =  ['is_completed']; 

         $todo->save() ;
         return  \Redirect::action('TodosController@index') ; 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $todo = Todo::findOrFail($id) ;

        return view('todo-show',  compact('todo') ) ; 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $todo = Todo::findOrFail($id) ;

        return view('todo-edit', compact('todo') ); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $todo =  Todo::where('id' ,$id)->first() ; 
        $todo->title =  $request->all()['title'] ; 
        $todo->body =  $request->all()['body'] ;
        $todo->is_completed=  isset($request->all()['is_completed'] ) ? 1 : 0 ; 

        if(isset($request->all()['is_completed']))  {

            $todo->completion_time =  \Carbon\Carbon::now()->toDateTimeString() ;
        }
        $todo->save() ; 

        return \Redirect::action('TodosController@index') ;  

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         Todo::destroy($id) ;
         return  \Redirect::action('TodosController@index') ; 

    }

    /**
     * complete a  todo 
     *
     * @param  int  $id
     * @param  Request $request 
     * @return \Illuminate\Http\Response
     */
    public function complete(Request $request , $id)
    {

        $todo= Todo::where('id',  $id)->first()  ;
        $todo->is_completed = 1 ; 
        $todo->completion_time =  \Carbon\Carbon::now()->toDateTimeString() ;
        $todo->save() ; 
        return \Redirect::action('TodosController@index') ; 

    } 
}

todoApp/resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
	<title> todoApp</title>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<style>
	.clearForm{
		display: inline;
    	border: none;
    	background: none;"
	}
</style>
<body>
 

	  <div class="container">
	  	<div class= "row">
	  		<div class="col-md-8 col-md-offset-2">
		  		@yield('content') 
		  	</div>
		</div>
	  </div>

</body>

</html>

todoApp/resources/views/todo-create.blade.php
@extends('layout')

@section('content')
	<h3> Create Todo</h3>
	{!! Form::open( array('route' => array('todoapp.store'), 'method' => 'POST')) !!}

<div class="form-group">

	{!! Form::text('title' ,null , ['class' => 'form-control', 'placeholder' => 'title'])  !!}
</div>

<div class="form-group">

	{!! Form::textarea('body', null ,  ['class' => 'form-control' ,'placeholder' => 'body ...'])  !!}
</div>

<div class="form-group">
<span > completed </span>
	{!! Form::checkbox('is_completed', '1')  !!}
</div>

<div class="form-group">
	{!! Form::submit('create',  ['class' => 'btn  btn-primary']) !!}
</div>
{!!Form::close()!!}

{!! link_to_route('todoapp.index', 'back', '', array('class'=> 'btn btn-success')) !!}
@stop  

todoApp/resources/views/todo-edit.blade.php
@extends('layout')


@section('content')

<h2> Edit Todo : </h2>
 
{!!
 Form::model($todo, array('route' => array('todoapp.update', $todo->id), 'method' => 'PUT')) !!}

<div class="form-group">
	{!! Form::text('title' ,null , ['class' => 'form-control'])  !!}
</div>

<div class="form-group">

	{!! Form::textarea('body', null ,  ['class' => 'form-control'])  !!}
</div>
<div class="form-group">
	<span>completed </span>
	{!! Form::checkbox('is_completed', '1' )  !!}
</div>

<div class="form-group">

	{!! Form::submit('Save',  ['class' => 'btn  btn-primary']) !!}
</div>
{!!Form::close()!!}
@stop  

todoApp/resources/views/todo-show.blade.php
@extends('layout')

@section('content')

<h2> Todo Details </h2>

  		<ul class="list-group">
		  		<li class="list-group-item">
		  			<h3>
		  				{{$todo->title}} 
		  			</h3>
		  			<hr>
		  			<div>
		  				{{$todo->body}}
		  			</div>
		  			<hr>
		  			<i>
			 			@if($todo->is_completed) 
			 			<span class="label label-success">Completed</span>
			 			@else 
			 				<span class="label label-danger">Not Completed</span>
			 			@endif
		  			</i> 
		  			@if($todo->is_completed) 
			  			<code>
			  				completion time  : {{$todo->completion_time}}
			  			</code>
		  			@endif

		  			<a href= "{{$todo->id}}/edit">
		  				<span class="glyphicon glyphicon-pencil"></span>
		  			</a>	
		  			@if(!$todo->is_completed) 
			  		<form action="complete/{{$todo->id}}" method="POST" class="clearForm">
	   				    <input type="hidden" name="_token" value="{{ csrf_token() }}">
	   				    <button class="clearForm" type="submit"  > <span class="glyphicon glyphicon-ok"></span> </button>
					</form>
					@endif

		  			<form action="{{$todo->id}}" method="POST" class="clearForm">
	   				    <input type="hidden" name="_token" value="{{ csrf_token() }}">
	   				        <input type="hidden" name="_method" value="DELETE">
	   				    <button class="clearForm" type="submit" > 
	   				    	<span class="glyphicon glyphicon-remove"></span> 
	   				    </button>
					</form>

		  		</li>
	  	</ul>
@stop  

todoApp/resources/views/todo.blade.php
@extends('layout')

@section('content')

<h3>  {{$todo->title}}</h3>
<hr>
<div>
	{{$todo->body}}
</div>

<code>{{$todo->completion_time}}</code>


@stop  

todoApp/resources/views/todos.blade.php
@extends('layout') 

@section('content') 	  	
  		<h1> All  todos</h1> 
  		<a href="todoapp/create" class= "btn btn-danger"> New </button></a>
  		<ul class="list-group">
		  	@foreach ($todos  as  $todo )
		  		<li class="list-group-item">
		  			<h3>
		  				<a href="todoapp/{{$todo->id}}">	{{$todo->title}} </a>
		  			</h3>
		  			<hr>
		  			<div>
		  				{{str_limit($todo->body, 90) }}
		  			</div>
		  			<hr>
		  			<i> 
			 			@if($todo->is_completed) 
			 			<span class="label label-success">Completed</span>
			 			@else 
			 				<span class="label label-danger">Not Completed</span>
			 			@endif
		  			</i>

		  			@if($todo->is_completed) 
			  			<code>
			  				completion time  : {{$todo->completion_time}}
			  			</code>
		  			@endif
		  			<a href= "todoapp/{{$todo->id}}/edit">
		  				<span class="glyphicon glyphicon-pencil"></span>
		  			</a>
					
					@if(!$todo->is_completed) 

			  		<form action="todoapp/complete/{{$todo->id}}" method="POST" class="clearForm">
	   				    <input type="hidden" name="_token" value="{{ csrf_token() }}">
	   				    <button class="clearForm" type="submit" class="clear"> <span class="glyphicon glyphicon-ok"></span> </button>
					</form>
					
					@endif
		  		
		  			<form action="todoapp/{{$todo->id}}" method="POST" class="clearForm">
	   				    <input type="hidden" name="_token" value="{{ csrf_token() }}">
	   				        <input type="hidden" name="_method" value="DELETE">
	   				    <button class="clearForm" type="submit" class="clear"> 
	   				    	<span class="glyphicon glyphicon-remove"></span> 
	   				    </button>
					</form>

		  		</li>
		  		<br>
		  	@endforeach  
	  	</ul>
	  	{!!$todos->render()!!}
@stop